USE DB_MYRH
GO

-- Trabalhando com subqueries (subconsultas)
SELECT * FROM TB_CARGOS
SELECT * FROM TB_INSCRICOES

-- Buscar todos os cargos (TB_CARGOS) que não possuam inscrição
SELECT * FROM TB_CARGOS WHERE ID NOT IN (SELECT DISTINCT ID_CARGO FROM TB_INSCRICOES)

SELECT * FROM TB_CARGOS WHERE ID BETWEEN 3 AND 5
SELECT * FROM TB_CARGOS WHERE ID = 3 OR ID = 4 OR ID = 5
SELECT * FROM TB_CARGOS WHERE ID IN (3, 4, 5)
