USE DB_MYRH
GO

-- 1. Exemplos de funções de agregação
SELECT 
	SUM(SALARIO) AS SOMA,
	AVG(SALARIO) AS MEDIA,
	MAX(SALARIO) AS MAXIMO,
	MIN(SALARIO) AS MINIMO,
	STDEV(SALARIO) AS [DESVIO PADRAO],
	COUNT(SALARIO) AS QUANTIDADE
FROM TB_CARGOS

-- 2. Aplicação da cláusula GROUP BY
SELECT 
	SUM(SALARIO) AS SOMA, 
	COUNT(*) AS QUANT,
	TP_SALARIO 
FROM 
	TB_CARGOS
GROUP BY 
	TP_SALARIO

-- 3. Usando uma consulta com todas as tabelas
SELECT 
	A.DESCRICAO AS AREA,
	C.DESCRICAO AS CARGO,
	SUM(C.SALARIO)  AS [SOMA SALARIO],
	COUNT(*) AS QUANTIDADE,
	C.TP_SALARIO AS TIPO,
	I.DATA_INSCRICAO AS DATA,
	CD.CPF AS CPF,
	CD.NOME AS CANDIDATO
FROM
	TB_AREAS A JOIN TB_CARGOS C ON A.ID = C.ID_AREA
	JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	JOIN TB_CANDIDATOS CD ON I.CPF = CD.CPF
GROUP BY
	A.DESCRICAO, C.DESCRICAO, C.TP_SALARIO,I.DATA_INSCRICAO,CD.CPF,CD.NOME


SELECT 
	A.DESCRICAO AS AREA,
	C.DESCRICAO AS CARGO,
	SUM(C.SALARIO)  AS [SOMA SALARIO],
	COUNT(*) AS QUANTIDADE,
	C.TP_SALARIO AS TIPO
FROM
	TB_AREAS A JOIN TB_CARGOS C ON A.ID = C.ID_AREA
	JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	JOIN TB_CANDIDATOS CD ON I.CPF = CD.CPF
GROUP BY
	A.DESCRICAO, C.DESCRICAO, C.TP_SALARIO



SELECT 
	SUM(C.SALARIO)  AS [SOMA SALARIO],
	COUNT(*) AS QUANTIDADE,
	C.TP_SALARIO AS TIPO,
	CD.CPF AS CPF,
	CD.NOME AS CANDIDATO
FROM
	TB_AREAS A JOIN TB_CARGOS C ON A.ID = C.ID_AREA
	JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	JOIN TB_CANDIDATOS CD ON I.CPF = CD.CPF
GROUP BY
	C.TP_SALARIO, CD.CPF, CD.NOME


SELECT 
	SUM(C.SALARIO)  AS [SOMA SALARIO],
	COUNT(*) AS QUANTIDADE,
	CD.CPF AS CPF,
	CD.NOME AS CANDIDATO
FROM
	TB_AREAS A JOIN TB_CARGOS C ON A.ID = C.ID_AREA
	JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	JOIN TB_CANDIDATOS CD ON I.CPF = CD.CPF
GROUP BY
	CD.CPF, CD.NOME

-- Exercício 01: Apresentar a quantidade de inscrições por área 
-- (somente 2 colunas na resposta: AREA e QUANTIDADE)
SELECT 
	A.DESCRICAO AS AREA,
	COUNT(*) AS [QTDE INSCRITOS]
FROM
	TB_AREAS A JOIN TB_CARGOS C ON A.ID = C.ID_AREA
	JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	--JOIN TB_CANDIDATOS CD ON I.CPF = CD.CPF
GROUP BY
	A.DESCRICAO



-- Exercício 02: Apresentar a quantidade de inscrições por cargo 
-- (somente 2 colunas na resposta: CARGO e QUANTIDADE)
SELECT 
	C.DESCRICAO AS CARGO,
	COUNT(*) AS [QTDE INSCRITOS]
FROM
	TB_CARGOS C JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	--TB_AREAS A JOIN TB_CARGOS C ON A.ID = C.ID_AREA
	--JOIN TB_INSCRICOES I ON C.ID = I.ID_CARGO
	--JOIN TB_CANDIDATOS CD ON I.CPF = CD.CPF
GROUP BY
	C.DESCRICAO